version: '3'

services:
  lambda: 
    build: .
    environment:
      - PYTHONPATH=/var/task/lambda/src:/var/task/lib
      - PATH=/var/task/bin:/var/task/bin/lib
    volumes:
      - ./lambda/src/:/var/task/lambda/src
      - ./tmp/:/tmp/
